### ISSUE TITLE
dragging from pixels near the resize handles causes weird drag interaction

### ISSUE THREAD

**Issue by ampersam** [trickford/plot#2]
If you attempt to drag the selection box by clicking within a dozen or so pixels of the side of the selection box or the handles, the interaction will work briefly but then cease to drag with the cursor. Sometimes the selection box will disappear or cease to respond all together until redrawing.

**Comment by trickford** [comment]
This is now fixed in 519c756bf74b59f2d1c398764e3d7e006bf28a6f
